pipeline {
    agent {
        dockerfile {
            dir 'ci'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'yarn'
            }
        }
        stage('Test') {
            steps {
                sh 'yarn test'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'development'
            }
            steps {
                sh 'yarn test:cov'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'echo \'finish development\''
            }
        }
        stage('Deploy for production') {
            when {
                branch 'master'
            }
            steps {
                sh 'yarn test:cov'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'echo \'finish production\''
            }
        }
    }
}
